# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r_github_packages:
  - r-lib/pkgdown
  - tidyverse/tidytemplate

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'

    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
      skip_cleanup: true
  - r: 3.5
  - r: 3.4
  - r: 3.3
  - r: 3.2

  allow_failures:
  - r: 3.2
